name: Build and Deploy MyWebApp

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Optional: manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ./MyWebApp

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./MyWebApp

      - name: Publish
        run: dotnet publish -c Release -o publish
        working-directory: ./MyWebApp

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: MyWebAppSandeep
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./MyWebApp/publish
